c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed as
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed at
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed bb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed ca
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed dd
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed ga
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed sb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt fed sc
 
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli as
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli at
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli bb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli ca
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli dd
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli ga
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli sb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt kli sc

c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori as
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori at
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori bb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori ca
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori dd
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori ga
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori sb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ori sc

c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind as
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind at
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind bb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind ca
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind dd
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind ga
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind sb
c:\progra~1\winbatch\system\winbatch k:\cwork\rotate.wbt ind sc

