/*****************************************************************************/
/*   Cflags.c: generated by mkcflags on Sun Jul 12, 1998          */
/*****************************************************************************/
#include "config.h"
#include <time.h>
#include INC_SYS_TIME

char cflags[]="cl /nologo /MT -DWIN32 /Ox /G5 /Zi";
char arch[]="Intel/Win32";
char cdate[]="";
struct timeval tv_ctime={900290022,0};
char cbugs[]="Send bugs/suggestion to: sheldon@visi.com";
char cowid[]="Netrek 2000pl0, Intel/Win32, , MCSE30AmTsr, Alpha ver. Caesar-0";
char cwho[]="sheldon@visi.com"; 
