#
# =========================================================================
# COW on Win32 Makefile
#
# This makefile is written for Microsoft Visual C++ 5.0
#
#

!INCLUDE system.mk

all: client

rsa: 
	cd rsa
	nmake
	cd ..

client:
	cd src
	nmake
	cd ..
