#define FED_torp   1
#define FED_torp_det   9
#define FED_plasma   14
#define FED_plasma_det   22
#define ORI_torp   27
#define ORI_torp_det   35
#define ORI_plasma   40
#define ORI_plasma_det   48
#define KLI_torp   53
#define KLI_torp_det   61
#define KLI_plasma   66
#define KLI_plasma_det   74
#define ROM_torp   79
#define ROM_torp_det   87
#define ROM_plasma   92
#define ROM_plasma_det   100
#define IND_torp   105
#define IND_torp_det   113
#define IND_plasma   118
#define IND_plasma_det   126
